engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  brakeman:
      enabled: true
  bundler-audit:
      enabled: true
  coffeelint:
      enabled: true
  fixme:
      enabled: true
  radon:
      enabled: true
  haxe-checkstyle:
      enabled: true
  markdownlint:
      enabled: true
  phan:
      enabled: true
  reek:
      enabled: true
  rubymotion:
      enabled: true
  shellcheck:
      enabled: true
  tailor:
      enabled: true
  vint:
      enabled: true
  eslint:
      enabled: true
  csslint:
      enabled: true
  duplication:
      enabled: true
    config:
        languages:
      - ruby
      	#mass_threshold: 30
      - javascript
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
- public/assets/**
