# config for scrutinizer-ci.com

checks:
    php:
        code_rating: true
        duplication: true

    python:
        code_rating: true
        duplicate_code: true

    ruby:
        code_rating: true
        duplicate_code: true



build:
    tests:
        override:
            -
                command: 'bundle exec rspec spec'
                environment:
                    'SCRUTINIZER_CC_FILE': 'my-coverage'
                coverage:
                    file: 'my-coverage'
                    format: 'rb-cc'
