# config for scrutinizer-ci.com

checks:
    ruby:
        code_rating: true
        duplicate_code: true

build:
    tests:
        override:
            -
                command: 'bundle exec rake test'
                environment:
                    'SCRUTINIZER_CC_FILE': 'my-coverage'
                    selenium: true
                coverage:
                    file: 'my-coverage'
                    format: 'rb-cc'
